### ISSUE TITLE
The Event 'OnAfterPreReport' is not found in target

### ISSUE THREAD

**Issue by jigneshdhandhanav** [finn777/ALF_Tracker_for_Adjust_Cost_Item_Entries#1]
In your project, Codeunit 50128 - ALF_Tracker_for_Adjust_Code. The event 'OnAfterPreReport' is not found in the target.

Currently I am configure your project in Business Central Base version in visual studio code.

Kindly let me know how to resolve this issue.

![onafterprereport](https://user-images.githubusercontent.com/46296969/51589615-89e47f00-1f0d-11e9-9396-3417e1554810.png)

**Comment by finn777** [comment]
Event OnAfterPreReport has been added on Report 795 Adjust Cost - Item Entries in 13.1, double check that your system 13.1 or higher

**Comment by finn777** [comment]
This change (REP795):
![image](https://user-images.githubusercontent.com/16433990/51607650-506c3d80-1f26-11e9-9e8f-aeeb98b7f846.png)

**Comment by finn777** [comment]
Hope this help.
